apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue-service
  template:
    metadata:
      labels:
        app: catalogue-service
    spec:
      containers:
        - name: catalogue-service
          image: catalogue-service:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-catalogue-service:5432/service1db
            - name: SPRING_DATASOURCE_USERNAME
              value: service1user
            - name: SPRING_DATASOURCE_PASSWORD
              value: service1pass
          