apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paiement-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-paiement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-paiement
  template:
    metadata:
      labels:
        app: postgres-paiement
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: service2db
            - name: POSTGRES_USER
              value: service2user
            - name: POSTGRES_PASSWORD
              value: service2pass
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: paiement-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-paiement-service
spec:
  selector:
    app: postgres-paiement
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP