name: Microservices CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ ma        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build discovery-service
        run: |
          cd discovery-service
          mvn clean install -DskipTests

      - name: Build config-service
        run: |
          cd config-service
          mvn clean install -DskipTests

      - name: Build catalogue-service
        run: |
          cd catalogue-service
          mvn clean -DskipTests

      - name: Build commande-service
        run: |
          cd commande-service
          mvn clean install -DskipTests

      - name: Build paiement-service
        run: |
          cd paiement-service
          mvn clean install -DskipTests

      - name: Build gateway-service
        run: |
          cd gateway-service
          mvn clean install -DskipTests
